config/routes.rb
Yrs2011Rails::Application.routes.draw do
  resources :patients do
    
    resources :prescriptions
    
    resources :maps
    
    resources :gps do
      resources :bookings
    end
    
    resources :static
  end
  
  match '/qrcode/:id/:signed_id' => 'qrcode#show'
  
  match '/patients/:patient_id/drugs' => 'drugs#show'
  
  root :to => 'static#index', :patient_id => 1
  
  match '/patients/:patient_id/history' => 'static#patient_history'
  
  match '/geocode' => 'geocode#show'
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  # GET /prescriptions
  # GET /prescriptions.xml
  def index
    @prescriptions = Prescription.find_all_by_patient_id params[:patient_id]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @prescriptions }
    end
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.xml
  def show
    require 'google-qr'
    require "#{RAILS_ROOT}/lib/qr_methods.rb"
    
    @prescription = Prescription.where( :id => params[:id],
                      :patient_id => params[:patient_id] ).first
                      
    id = @prescription.id
    signed_output = @prescription.signature
    signed_id_trunc = signed_output.lines.to_a[3..-2].join.gsub(/\n/,'')[-15,15]
    @image_path = qr_code_from_id id, signed_id_trunc 

  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/index.html.erb
<div class="centre">
  <h1>My Prescriptions</h1>
  <h2>Drugs</h2>
  <p>
    Search using the box below to find drug information.
    <%= form_tag "/patients/#{params[:patient_id]}/drugs", :method => :get do %>
      <%= text_field_tag "name" %>
      <%= submit_tag "Search", :class => "button blue bigrounded" %>
    <% end %>
  </p>
  <br/>
  <br/>

  <h2>Previous prescriptions</h2>
</div>
<table>
  <tr>
    <th>Prescription ID</th>
    <th>DIN</th>
    <th>Item</th>
    <th>Strength</th>
    <th>Amount</th>
    <th>When</th>
    <th></th>
    <th></th>
  </tr>

<% @prescriptions.each do |prescription| %>
  <tr>
    <td><%= prescription.id %></td>
    <td><%= prescription.din %></td>
    <td><%= prescription.item %></td>
    <td><%= prescription.strength %></td>
    <td><%= prescription.amount %></td>
    <td><%= prescription.when %></td>
    <td><%= link_to 'Show', patient_prescription_path(params[:patient_id], prescription) %></td>
    <td><%= link_to 'Renew', patient_prescription_path(params[:patient_id], prescription) %></td>
  </tr>
<% end %>
</table>

app/views/prescriptions/show.html.erb
<% content_for :header_includes do %>
<script type="text/javascript">
  $(document).ready(function() {
    // Redirect iPhone/iPod visitors
    // http://jquery-howto.blogspot.com/2010/09/iphone-ipod-detection-using-jquery.html
    function isiPhone(){
      return (
        (navigator.platform.indexOf("iPhone") != -1) ||
        (navigator.platform.indexOf("iPod") != -1)
      );
    }
    
    if isiPhone() {
      $('div.header').hide();
      $('div#qr_code').hide();
    }
  });
</script>
<% end %>

<p id="notice"><%= notice %></p>
<div id="prescription_content">
<p>
  <b>Name:</b>
  <%= @patient.name %>
</p>

<p>
  <b>Address:</b>
  <%= @patient.address_line_one %>,<br/>
  <%= @patient.town %>,<br/>
  <%= @patient.county %>,<br/>
  <%= @patient.postcode %>,<br/>
</p>

<p>
  <b>Din:</b>
  <%= @prescription.din %>
</p>

<p>
  <b>Item:</b>
  <%= @prescription.item %>
</p>

<p>
  <b>Strength:</b>
  <%= @prescription.strength %>
</p>

<p>
  <b>Amount:</b>
  <%= @prescription.amount %>
</p>

<p>
  <b>When:</b>
  <%= @prescription.when %>
</p>
<%= link_to 'Back', patient_prescriptions_path(params[:patient_id]) %>
</div>

<div id="qr_code">
  <b>QR Code:</b><br/>
  <%= image_tag @image_path, :width => 500 %>
</div>