config/routes.rb
Yrs2011Rails::Application.routes.draw do
  resources :patients do
    
    resources :prescriptions
    
    resources :maps
    
    resources :gps do
      resources :bookings
    end
    
    resources :static
  end
  
  match '/qrcode/:id/:signed_id' => 'qrcode#show'
  
  match '/patients/:patient_id/drugs' => 'drugs#show'
  
  root :to => 'static#index', :patient_id => 1
  
  match '/patients/:patient_id/history' => 'static#patient_history'
  
  match '/geocode' => 'geocode#show'
end

app/models/booking.rb
class Booking < ActiveRecord::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  before_filter :get_gp
  
  # GET /gps/1/bookings
  # GET /gps/1/bookings.ics
  def index
    session[:filter] = params[:filter]
    respond_to do |format|
      format.html {  }
      format.ics {
        @bookings = Booking.where( :user_id => params[:patient_id]).where( "time > ?",
                      Time.now )
        @calendar = Icalendar::Calendar.new
    
        @bookings.each do |booking|
          event = Icalendar::Event.new
          event.start = booking.time.strftime("%Y%m%dT%H%M%S")
          event.start = (booking.time + 15.minutes).strftime("%Y%m%dT%H%M%S")
          event.summary = "GP Appointment"
          event.description = booking.message
          event.location = @gp_location
          @calendar.add event
        end
    
        @calendar.publish
          render :text => @calendar.to_ical
      }
    end
  end

  # GET /gps/1/bookings/1
  def show
    @booking = Booking.find(params[:id])
  end

  # GET /gps/1/bookings/new
  def new
    @booking = Booking.new
    # If the time to create the new appointment for is preset, use it
    @time = params[:time] unless params[:time].nil?
  end

  # GET /gps/1/bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /gps/1/bookings
  def create
    preset_options = { :user_id => params[:patient_id], :gp_id => @gp_id }
    options = params[:booking].merge preset_options
    
    @booking = Booking.new options

    if @booking.save
      redirect_to patient_gp_booking_path(:patient_id => params[:patient_id],
        :gp_id => @gp_id, :id => @booking.id), 
        :notice => 'Booking was successfully created.'
    else
      render :action => "new" 
    end
  end

  # PUT /gps/1/bookings/1
  def update
    @booking = Booking.find(params[:id])

    if @booking.update_attributes(params[:booking])
      redirect_to @booking, :notice => 'Booking was successfully updated.'
    else
      render :action => "edit"
    end
  end
  
  private
  def get_gp
    @gp_id = params[:gp_id]
    @gp_location = "TN22 2HT"
    @gp_name = "Dr. Sivraj"
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<% content_for :header_includes do %>
  <%= stylesheet_link_tag "bookings" %>
<% end %>
<div class="bookings_container">
<%= form_for @booking, :url => patient_gp_bookings_path do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @time %>
    <%= f.hidden_field :time, :value => @time %>
  <% else %>
    <div class="field">
      <br />
      <%= f.datetime_select :time, :minute_step => 20 %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message, :value => "Please fill in with the reason you" +
      " would like to visit your GP" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "button blue bigrounded" %>
  </div>
<% end %>
</div>

app/views/bookings/edit.html.erb
<% content_for :header_includes do %>
  <%= stylesheet_link_tag "bookings" %>
<% end %>
<div class="bookings_container">

<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>
</div>

app/views/bookings/index.html.erb
<% content_for :header_includes do %>
  <%= stylesheet_link_tag "bookings" %>
  <script type="text/javascript">
  $(document).ready(function() {
    $('select#filter').change(function() {
      window.location.href = "<%= patient_gp_bookings_path %>?filter=" + $(this).val();
    });
  });
  </script>
<% end %>
<div class="bookings_container">

<h1>Bookings for GP <%= @gp_name %></h1>
<div class="nav_links">
  <%= link_to 'New Booking', new_patient_gp_booking_path %> |
  <%= link_to image_tag("ical.gif"), patient_gp_bookings_path(:format => :ics) %>
</div>

<div class="key_wrapper">
  <a id="showhide_key" href="#">Key</a>
</div>
<div class="key">
  <table class="key">
    <% if params[:filter] and params[:filter] == "user" %>
      <tr>
        <td class="user_booked key"></td>
        <td>Already booked by you</td>
      </tr>
      <tr>
        <td class="booked key"></td>
        <td>Already booked by someone else</td>
      </tr>
    <% else %>
      <tr>
        <td class="booked key"></td>
        <td>Already booked</td>
      </tr>
    <% end %>
    <tr>
      <td class="unbooked key"></td>
      <td>Not yet booked</td>
    </tr>
  </table>
</div>


<div class="filter_bookings">
  <% option_tags = "<option selected value='all'>All Bookings</option><option value='user'>My Bookings</option>" %>
  <% option_tags = "<option value='all'>All Bookings</option><option selected value='user'>My Bookings</option>" if
      params[:filter] and params[:filter] == "user" %>
  <%= select_tag 'filter', option_tags.html_safe %>
</div>

<%# http://www.ruby-forum.com/topic/187461 %>
<% t_now = Time.now %>
<% t_prev_mon_begin = t_now - (t_now.wday-1)*24*60*60 - t_now.hour*60*60 - t_now.min*60 - t_now.sec %>
<br/><h3>For week beginning <%= t_prev_mon_begin.strftime "%d/%m/%Y" %></h3>
<table class="bookings">
  <tr>
    <th></th>
    <% start_time = (Time.now.beginning_of_day + 10.hours).to_i %>
    <% end_time = (Time.now.beginning_of_day + 16.hours).to_i %>
    <% Range.new(start_time, end_time).step(20.minutes) do |seconds| %>
      <% time = Time.at(seconds) %>
      <th><%= time.strftime "%H:%M"" "%></th>
    <% end %>
  </tr>
  <% (1..6).each do |day| %>
    <tr>
      <th><%= Date::DAYNAMES[day][0..2] %></th>
      <% Range.new(start_time, end_time).step(20.minutes) do |seconds| %>
        <% time = Time.at(seconds) %>
        <% day_time = Time.mktime time.year, time.month, day, time.hour,
            time.min %>
        <% all_bookings = Booking.find_all_by_time day_time %>
        <% if params[:filter] == "user" %>
          <% bookings = Booking.where :user_id => params[:patient_id],
              :time => day_time %>
        <% end %>
        <% if bookings and bookings.first %>
          <td class="user_booked">
            <%= link_to "Booked by you", patient_gp_booking_path(:id => bookings.first.id) %>
        <% elsif all_bookings and all_bookings.first %>
          <td class="booked">
            Booked
        <% else %>
          <td class="unbooked">
            <%= link_to "Book", new_patient_gp_booking_path(:time => day_time) %>
        <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<div class="credit">
  ICAL logo CC-licensed from <%= link_to "mokolabs",
    "http://www.flickr.com/photos/mokolabs/127824172/" %>
</div>
</div>

app/views/bookings/new.html.erb
<% content_for :header_includes do %>
  <%= stylesheet_link_tag "bookings" %>
<% end %>
<div class="bookings_container">

<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', patient_gp_bookings_path %>
</div>

app/views/bookings/show.html.erb
<% content_for :header_includes do %>
  <%= stylesheet_link_tag "bookings" %>
<% end %>
<div class="bookings_container">

<p id="notice"><%= notice %></p>

<p>
  <b>GP:</b>
  <%= @booking.gp_id %>
</p>

<p>
  <b>Time:</b>
  <%= @booking.time %>
</p>

<p>
  <b>Message:</b>
  <%= @booking.message %>
</p>


<%= link_to 'Back', patient_gp_bookings_path(:filter => session[:filter]) %>

</div>