config/routes.rb
Yrs2011Rails::Application.routes.draw do
  resources :patients do
    
    resources :prescriptions
    
    resources :maps
    
    resources :gps do
      resources :bookings
    end
    
    resources :static
  end
  
  match '/qrcode/:id/:signed_id' => 'qrcode#show'
  
  match '/patients/:patient_id/drugs' => 'drugs#show'
  
  root :to => 'static#index', :patient_id => 1
  
  match '/patients/:patient_id/history' => 'static#patient_history'
  
  match '/geocode' => 'geocode#show'
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :history_items
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  
  skip_before_filter :get_user
  
  # GET /patients
  # GET /patients.xml
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.xml
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.xml
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.xml
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to(@patient, :notice => 'Patient was successfully created.') }
        format.xml  { render :xml => @patient, :status => :created, :location => @patient }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.xml
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to(@patient, :notice => 'Patient was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.xml
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to(patients_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address_line_one %><br />
    <%= f.text_field :address_line_one %>
  </div>
  <div class="field">
    <%= f.label :town %><br />
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :county %><br />
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br />
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :gp_id %><br />
    <%= f.text_field :gp_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address line one</th>
    <th>Town</th>
    <th>County</th>
    <th>Postcode</th>
    <th>GP ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patients.each do |patient| %>
  <tr>
    <td><%= patient.name %></td>
    <td><%= patient.address_line_one %></td>
    <td><%= patient.town %></td>
    <td><%= patient.county %></td>
    <td><%= patient.postcode %></td>
    <td><%= patient.gp_id %></td>
    <td><%= link_to 'Show', patient %></td>
    <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
    <td><%= link_to 'Destroy', patient, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @patient.name %>
</p>

<p>
  <b>Address line one:</b>
  <%= @patient.address_line_one %>
</p>

<p>
  <b>Town:</b>
  <%= @patient.town %>
</p>

<p>
  <b>County:</b>
  <%= @patient.county %>
</p>

<p>
  <b>Postcode:</b>
  <%= @patient.postcode %>
</p>

<p>
  <b>GP ID:</b>
  <%= @patient.gp_id %>
</p>


<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>