config/routes.rb
Yrs2011Rails::Application.routes.draw do
  resources :patients do
    
    resources :prescriptions
    
    resources :maps
    
    resources :gps do
      resources :bookings
    end
    
    resources :static
  end
  
  match '/qrcode/:id/:signed_id' => 'qrcode#show'
  
  match '/patients/:patient_id/drugs' => 'drugs#show'
  
  root :to => 'static#index', :patient_id => 1
  
  match '/patients/:patient_id/history' => 'static#patient_history'
  
  match '/geocode' => 'geocode#show'
end

app/models/booking.rb
class Booking < ActiveRecord::Base
end

app/models/geocode.rb
class Geocode < Hashie::Mash
  include HTTParty
  base_uri "http://maps.googleapis.com/maps/api/geocode"
  format :json
  
  def self.geocode(query)
    self.new get('/json', :query => query)
  end
    #Get http://maps.googleapis.com/maps/api/geocode/json?options
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :history_items
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
end

app/models/wikipedia.rb
class Wikipedia < Hashie::Mash  
  include HTTParty
  require 'nokogiri'
  base_uri "http://simple.wikipedia.org/w"
  
  def self.find_overview(page_name)
    page_name.downcase!
    
    query = { :action => "render", :rvprop => "content", :title => page_name }
    
    headers = {"User-Agent" => "Ruby/Rails Contact hrickards@gmail.com"}
    
    data_whole = get('/index.php?', :query => query, :headers => headers).to_s
    
    unless data_whole["Wikipedia does not yet have an article with this name"].nil?
      base_uri "http://en.wikipedia.org/w"
      data_whole = get('/index.php?', :query => query, :headers => headers).to_s
    end
    
    parsed_whole = Nokogiri::HTML(data_whole).xpath("//body").to_html
    index = parsed_whole.index("<h2")
    
    data_overview = parsed_whole[0,index]
    parsed_overview = Nokogiri::HTML(data_overview).xpath("//p").to_html
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  before_filter :get_gp
  
  # GET /gps/1/bookings
  # GET /gps/1/bookings.ics
  def index
    session[:filter] = params[:filter]
    respond_to do |format|
      format.html {  }
      format.ics {
        @bookings = Booking.where( :user_id => params[:patient_id]).where( "time > ?",
                      Time.now )
        @calendar = Icalendar::Calendar.new
    
        @bookings.each do |booking|
          event = Icalendar::Event.new
          event.start = booking.time.strftime("%Y%m%dT%H%M%S")
          event.start = (booking.time + 15.minutes).strftime("%Y%m%dT%H%M%S")
          event.summary = "GP Appointment"
          event.description = booking.message
          event.location = @gp_location
          @calendar.add event
        end
    
        @calendar.publish
          render :text => @calendar.to_ical
      }
    end
  end

  # GET /gps/1/bookings/1
  def show
    @booking = Booking.find(params[:id])
  end

  # GET /gps/1/bookings/new
  def new
    @booking = Booking.new
    # If the time to create the new appointment for is preset, use it
    @time = params[:time] unless params[:time].nil?
  end

  # GET /gps/1/bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /gps/1/bookings
  def create
    preset_options = { :user_id => params[:patient_id], :gp_id => @gp_id }
    options = params[:booking].merge preset_options
    
    @booking = Booking.new options

    if @booking.save
      redirect_to patient_gp_booking_path(:patient_id => params[:patient_id],
        :gp_id => @gp_id, :id => @booking.id), 
        :notice => 'Booking was successfully created.'
    else
      render :action => "new" 
    end
  end

  # PUT /gps/1/bookings/1
  def update
    @booking = Booking.find(params[:id])

    if @booking.update_attributes(params[:booking])
      redirect_to @booking, :notice => 'Booking was successfully updated.'
    else
      render :action => "edit"
    end
  end
  
  private
  def get_gp
    @gp_id = params[:gp_id]
    @gp_location = "TN22 2HT"
    @gp_name = "Dr. Sivraj"
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  def show
     @title = params[:name]
     @page = Wikipedia.find_overview @title
  end
end

app/controllers/geocode_controller.rb
class GeocodeController < ApplicationController
  skip_before_filter :get_user
  
  def show
    options = params
    options.delete "action"
    options.delete "controller"
    data = Geocode.geocode options
    render :json => data
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  
  def index
  end
end

app/controllers/qrcode_controller.rb
class QrcodeController < ApplicationController
  skip_before_filter :get_user
  
  def show
    @prescription = Prescription.find params[:id]
    notice = "Prescription electronically signed by doctor hrickards+foobar@gmail.com"
    redirect_to patient_prescription_path(@prescription.patient_id, params[:id]), :notice => notice
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
  
  def patient_history
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/geocode_helper.rb
module GeocodeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/helpers/qrcode_helper.rb
module QrcodeHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myNHS</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= javascript_include_tag :all %>
  <%= yield :header_includes %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container">
  <div class="header">
    <div id="logo">
      <%= image_tag "logo.png", :width => 300 %>
    </div>
    <% unless controller.controller_name == "patients" or controller.controller_name == "geocode" %>
        <div id="navcontainer">
      <div class="main_nav_links">
        <ul id="navlist">
          <% css_class = "tab" %>
          <% css_class = "current" if controller.controller_name == "static" and controller.action_name == "index" %>
          <li><%= link_to "Home", url_for(:controller => "static", :action => "index"), :class => css_class %></li>
          <% css_class = "tab" %>
          <% css_class = "current" if controller.controller_name == "maps" %>
          <li><%= link_to "Medical Map", patient_maps_path, :class => css_class  %></li>
          <% css_class = "tab" %>
          <% css_class = "current" if controller.controller_name == "bookings" %>
          <li><%= link_to "Book an Appointment", patient_gp_bookings_path(params[:patient_id], @patient.gp_id), :class => css_class  %></li>
          <% css_class = "tab" %>
          <% css_class = "current" if controller.controller_name == "prescriptions" %>
          <li><%= link_to "My Prescriptions", patient_prescriptions_path(params[:patient_id]), :class => css_class  %></li>
          <% css_class = "tab" %>
          <% css_class = "current" if controller.controller_name == "static" and controller.action_name == "patient_history" %>
          <li><%= link_to "My History", url_for(:controller => "static", :action => "patient_history"), :class => css_class  %></li>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <%= yield %>
</div>
</body>
</html>